import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import "./globals.css";
import styles from '@/app/page.module.css'
import Header from "@/app/components/Header";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body className={inter.className}>
          <div className={styles.header_wrapper}>
            <Header />
          </div>
          <div className={styles.body_container}>
          {children}
          </div>
         
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
